### ISSUE TITLE
Being able to input various commands that will be executed sequentially

### ISSUE THREAD

**Issue by takashi1kun** [Tardo/OdooTerminal#101]
The idea would be to be able to put various commands at once and then press enter, and it will execute the first, wait for response, execute the second, wait for response, etc.
Basically will always try to wait for the previous one to do the next one, this would be useful for upgrade/install commands, something like 
multi -c ual; upgrade -m module1; upgrade -m module2; upgrade -m module3; install -m module4;  upgrade -m module5; print finished; 
Or something like 
multi-commands(enter)(enters in multi command mode)(prints text "Introduce commands and write execute to start")
ual(enter)(does nothing)
upgrade -m module(enter)(does nothing)
etc(enter)(does nothing)
execute(enter)(executes the commands)

But tbh i would prefer to put them all in the same command separated by ; or some other separator.

**Comment by Tardo** [comment]
Hi! If you are using the latest version (9.2.1) of the extension you should currently be able to do so:

`ual; upgrade -m module1; upgrade -m module2; upgrade -m module3; install -m module4; upgrade -m module5; print finished;`

In the next version you will be able to do something like (in the current version it has a bug):
`$modules = [module1,module2,module3,module4,module5]; repeat -t $(($modules['length'] - 1)) -c "upgrade $modules[$(gen intiter)]"` 

** If you mean something else, tell me.
