### ISSUE TITLE
[BUG] TypeError: keys must be str, int, float, bool or None, not frozendict

### ISSUE THREAD

**Issue by wai** [Tardo/OdooTerminal#118]
**Basic Info. (please complete the following information):**
 - Odoo version: 16.0
 - Browser: chrome
 - Command: `read -m account.move.line -i 1 -f *`

**Describe the bug**
I test those on Odoo runbot

On Odoo 15.0, 16.0 Work like a charm! 
`read -m res.partner -i 1 -f *`

Some modules on Odoo 16.0 do not work, such as 
`read -m account.move.line -i 1 -f *`

But that is no problem on Odoo 15.0

**Expected behavior**
Read all fields of the record

**Comment by Tardo** [comment]
Fixed in 10.0.0: https://github.com/Tardo/OdooTerminal/pull/121
