### ISSUE TITLE
[BUG] Unregistered user

### ISSUE THREAD

**Issue by dewingarcia** [Tardo/OdooTerminal#123]
Lastest Version odoo terminal

**Basic Info.:**
 - Odoo version: 12.0, 13.0, 14.0
 - Browser: edge, firefox

**Describe the bug**
freeze when load the odoo. appears message 'Unregistered User         ip_dns_odoo.site'
in console show 
[OdooTerminal] Can't initilize longpolling:  InternalError: too much recursion terminal.mjs:1:60392

**Screenshots**
![Screen Shot 2023-08-16 at 15 00 05](https://github.com/Tardo/OdooTerminal/assets/11951010/684e98e5-16e0-400e-b433-d31ce719fe17)

**Comment by Tardo** [comment]
I am not able to replicate the issue, can you pass me a runbot environment where you have the problem?

For example, here: https://49481887-14-0-all.runbot177.odoo.com/

Thanks.

**Comment by dewingarcia** [comment]
in this address i have the same problem

![image](https://github.com/Tardo/OdooTerminal/assets/11951010/6be38e62-e80e-4d0e-b1ce-9ece7e168c7d)

**Comment by Tardo** [comment]
Ummm... You have any configuration in the extension options? windows?

**Comment by dewingarcia** [comment]
![image](https://github.com/Tardo/OdooTerminal/assets/11951010/d8c93d64-dd28-4015-8784-c4dba7136848)

init commands;
alias -n st -c "settings $1"
alias -n cs -c "clear -s screen"
alias -n c -c "clear -s screen"
alias -n i -c "install -m $1; now; reload"
alias -n un -c "uninstall -m $1; reload"
alias -n u -c "upgrade -m $1; now; reload"
alias -n v -c "view -m $1"
alias -n v_product -c "view -m product.product"
alias -n es_act -c "$lang_es = $(search -m res.lang -d [['code', 'like', 'es_ES'], ['active', 'in', [True, False]]]); call res.lang load_lang [$lang_es[0], 'es_ES']; tr $1"

**Comment by Tardo** [comment]
Ok! thanks. researching...

**Comment by dewingarcia** [comment]
Traceback firefox
Error:


Traceback:
Error: too much recursion
htmlPrefilter@https://49481887-14-0-all.runbot177.odoo.com/web/content/1492-0376fb9/1/web.assets_common_lazy.js:1689:57
html/<@https://49481887-14-0-all.runbot177.odoo.com/web/content/1492-0376fb9/1/web.assets_common_lazy.js:1696:129
access@https://49481887-14-0-all.runbot177.odoo.com/web/content/1492-0376fb9/1/web.assets_common_lazy.js:1553:21
html@https://49481887-14-0-all.runbot177.odoo.com/web/content/1492-0376fb9/1/web.assets_common_lazy.js:1695:309
updateInputInfo@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:37798
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:33441
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:48889
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812
execute@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50185
start@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:49013
#Ce@moz-extension://314c731a-8d85-4baf-8773-64efc77d648d/src/dist/terminal.mjs:1:50812

trace error edge
Error:


Traceback:
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Function.htmlPrefilter (https://49481887-14-0-all.runbot177.odoo.com/web/content/1492-0376fb9/1/web.assets_common_lazy.js:1689:57)
    at buildFragment (https://49481887-14-0-all.runbot177.odoo.com/web/content/1492-0376fb9/1/web.assets_common_lazy.js:1610:563)
    at jQuery.parseHTML (https://49481887-14-0-all.runbot177.odoo.com/web/content/1492-0376fb9/1/web.assets_common_lazy.js:1958:8)
    at new jQuery.fn.init (https://49481887-14-0-all.runbot177.odoo.com/web/content/1492-0376fb9/1/web.assets_common_lazy.js:1510:124)
    at jQuery (https://49481887-14-0-all.runbot177.odoo.com/web/content/1492-0376fb9/1/web.assets_common_lazy.js:1336:58)
    at #H (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/src/dist/terminal.mjs:1:40998)
    at Se.start (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/src/dist/terminal.mjs:1:33402)
    at je.start (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/src/dist/terminal.mjs:1:48890)
    at #Ce (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/src/dist/terminal.mjs:1:50813)

**Comment by Tardo** [comment]
Fixed here: https://github.com/Tardo/OdooTerminal/commit/a8a38e587e6ca10b2653b49f2ffe90790459e2d8

I will upgrade to 10.1.1 today to apply this fix. Thanks.

**Comment by dewingarcia** [comment]
thanks!!!

**Comment by dewingarcia** [comment]
it works perfectly! Thanks!
