### ISSUE TITLE
Samples in the console itself

### ISSUE THREAD

**Issue by reinaldoBloopark** [Tardo/OdooTerminal#124]
This is just a suggestion. It would be helpful if we could access it somehow from the same console to the examples. I am starting to use this tool, and every time I have to come the the repo to see the examples in the README. 

Can you add a section in the console where these examples are shown?

**Comment by Tardo** [comment]
Hi, using 'help' command you can see an example for every command.

For example: ```help search```

In the next version the "command assistant" will show a description... so you can know the order of the arguments, the name and description.
You can see the "command assistant" while typing... but in the current version is a bit bugged (not has a background).

I don't know if this is enough or you mean a more generic documentation of how TraSH (the pseudo-language used in the terminal) works.

**Comment by reinaldoBloopark** [comment]
This sounds great. I did not test `help`. I did now, and it's perfect. This was what I was looking for :) 

Great project, by the way. I wish I could help anyhow. Let me know if you need some help.
