### ISSUE TITLE
[BUG] clear command: can't access private field or method: object is not the right class 

### ISSUE THREAD

**Issue by WeeskyBDW** [Tardo/OdooTerminal#126]
First of all, check that you are using the latest version.
**Basic Info. (please complete the following information):**
 - Odoo terminal version: 10.3.1
 - Odoo version: 15.0 & 16.0 (not tested in 14.0)
 - Browser: Firefox 118.0.1
 - Command: `clear -s screen`

**Describe the bug**
When executing command `clear -s screen` i have "can't access private field or method: object is not the right class" error in the shell

**Expected behavior**
Clear terminal of previous commands and results

**Screenshots**
![image](https://github.com/Tardo/OdooTerminal/assets/36575072/06e7d332-be83-4283-bf50-6057187d0e98)
![image](https://github.com/Tardo/OdooTerminal/assets/36575072/ad4ba608-d70b-4051-88e3-4f455e65f5da)

**Additional context**

**Comment by Tardo** [comment]
Thanks for the report! Must be fixed in 10.3.2: https://github.com/Tardo/OdooTerminal/commit/690f80b4a616eca88ced6b50624937f252d266e0

**Comment by WeeskyBDW** [comment]
That work in 10.3.2 thx u so much
