### ISSUE TITLE
Commands autocomplete

### ISSUE THREAD

**Issue by WeeskyBDW** [Tardo/OdooTerminal#127]
**Is your feature request related to a problem? Please describe.**
When doing a lot of commands with odoo terminal, it's pretty painfull to have to manually type modules/models name

**Describe the solution you'd like**
I was thinking to a per-command function called when user type a command and then a space (example: `upgrade `) and then every command would have their function to implement autocomplete by overriding that function and return an array of choices depending of what possible and what user started to type

**Describe alternatives you've considered**
None yet 

**Additional context**
None

**Comment by Tardo** [comment]
@WeeskyBDW something like this? 
![oterm_options](https://github.com/Tardo/OdooTerminal/assets/731270/39faf17f-f487-4a65-ad75-ff48527d2e01)

**Comment by Tardo** [comment]
Done in 10.4.0

**Comment by WeeskyBDW** [comment]
Thx u so much
