### ISSUE TITLE
[BUG] Cannot do mass operation like the tutorial

### ISSUE THREAD

**Issue by phamgiang2510** [Tardo/OdooTerminal#128]
**Basic Info. (please complete the following information):**
 - Odoo version: All versions
 - Browser: Chrome
 - Command: `$orders = $(search sale.order -d [['state','=','draft']]); repeat -t $orders['length'] -c "call sale.order action_cancel [$orders[$(gen intiter)]['id']]"`

**Describe the bug**
I tried to do a mass cancellation on quotations like the tutorial, but errors occurred.

**Expected behavior**
Cancellation successfully.

**Screenshots**
![image](https://github.com/Tardo/OdooTerminal/assets/45560757/6a509e0e-a142-4c65-b47c-641a8bfae8aa)

**Comment by Tardo** [comment]
Thanks for report!

I need to update the readme :/ ... Try using ```$repeat_index``` instead of ```$(gen intiter)```

**Comment by phamgiang2510** [comment]
> Thanks for report!
> 
> I need to update the readme :/ ... Try using `$repeat_index` instead of `$(gen intiter)`

Still no luck 😢 Did I miss something?

Command: `$orders = $(search sale.order -d [['state','=','draft']]); repeat -t $orders['length'] -c "call sale.order action_cancel [$orders[$repeat_index]['id']]"`

Result:
![image](https://github.com/Tardo/OdooTerminal/assets/45560757/98763c05-df07-419b-bdfd-59e6fe254ac1)

**Comment by Tardo** [comment]
Fixed in 10.4.1

Thanks.
