### ISSUE TITLE
[BUG] In Odoo SaaS versions, you cannot see the real version in the extension icon

### ISSUE THREAD

**Issue by yajo** [Tardo/OdooTerminal#129]
First of all, check that you are using the latest version.

**Basic Info. (please complete the following information):**
 - Odoo version: saas-16.1
 - Browser: firefox
 - Command: None. Just looking at the icon

**Describe the bug**
The icon does not display the full version string, because it's too small.

**Expected behavior**
It would be nice if the version string could span 2 lines, just to be able to see which saas version is being used.

**Screenshots**
 ![imagen](https://github.com/Tardo/OdooTerminal/assets/973709/3122d713-1422-4309-803e-e9d2706a7c0f)

**Additional context**
Just open a runbot of any saas-16.1 edition (or newer)

**Comment by Tardo** [comment]
Ey Yajo! Thx for the report. I have removed the text 'saas~' and changed the color of the badge:

'Normal':
![badge_n](https://github.com/Tardo/OdooTerminal/assets/731270/5dea21cd-11d1-4583-81f8-56a7539338f2)

'Saas':
![badge_s](https://github.com/Tardo/OdooTerminal/assets/731270/3088f109-26f8-4293-86ab-efe3434c3eb8)

**Comment by yajo** [comment]
Cool, thanks!

**Comment by Tardo** [comment]
Done in 10.4.2
