### ISSUE TITLE
[BUG] Extension disabled in Odoo 16.1+

### ISSUE THREAD

**Issue by yajo** [Tardo/OdooTerminal#130]
**Basic Info. (please complete the following information):**
 - Odoo version: saas-16.1, saas-16.2, saas-16.3, saas-16.4, 17.0
 - Browser: firefox
 - Command: None.

**Describe the bug**
The extension is disabled.

**Expected behavior**
Enabled.

**Screenshots**
Enabled in 16.0: ![imagen](https://github.com/Tardo/OdooTerminal/assets/973709/db5d2b93-69e8-4a74-8036-a97c64b885a1)

Disabled in 17.0: ![imagen](https://github.com/Tardo/OdooTerminal/assets/973709/2e89e74e-cfc1-4abc-aa41-c460c5337dd3)

**Comment by Tardo** [comment]
Odoo >16.0 enabled in 10.4.2
