### ISSUE TITLE
Env variables for `ACTIVE_ID` and `ACTIVE_MODEL`

### ISSUE THREAD

**Issue by ivantodorovich** [Tardo/OdooTerminal#131]
First of all, I wanna thank you for this amazing tool ❤️
I have integrated it into my flow and it has saved me quite a lot of time already

---

**Is your feature request related to a problem? Please describe.**
Not really a problem, just something I wish it was possible.
I often use this tool to read hidden or missing fields on a record form.
For example, I navigate to a `sale.order` record, get the id from the browser URL, and use `read sale.order ID field1,field2`

**Describe the solution you'd like**
I'd like to be able to execute something like `read $ACTIVE_MODEL $ACTIVE_ID field1,field2`, where `ACTIVE_MODEL` and `ACTIVE_ID` would be inferred from the page.

---

Is this something you'd be interested in?
I'd be happy to contribute to make it happen (any pointers to get me started would be welcomed, too)

**Comment by Tardo** [comment]
Thanks! 
Sounds like a good idea! I'm just finishing tuning the use of FlowJS. As soon as I have it ready (should be this weekend) I'll get on this.

**Comment by Tardo** [comment]
I think the best way to approach it is with a command.
Something like ```ares``` (active resource) and, for example: ```search -m $(ares -m)```

Then enhance TraSH to have lambda functions and be able to do something like: ```$ACTIVE_MODEL = lambda: ares -m``` (not final syntax xD) and then be able to use ```$ACTIVE_MODEL```

**Comment by Tardo** [comment]
I have this ready... I have to see the compatibility with different Odoo versions of the new “url” command.

TraSH already supports functions and logical operations :) Anybody asked for it? Anybody needs it? No! but that's life.
![fuunc](https://github.com/Tardo/OdooTerminal/assets/731270/c2abbbf3-83d5-43f2-92ef-f39aab9dd912)

**Comment by Tardo** [comment]
![](https://i.kym-cdn.com/photos/images/facebook/001/243/355/3b5.png)

finally the syntax is:
$$RMOD - Active model
$$RID - Active ID
