### ISSUE TITLE
[BUG] `debug` doesn't work in newer versions

### ISSUE THREAD

**Issue by Desdaemon** [Tardo/OdooTerminal#132]
**Basic Info:**
 - Odoo version: 17.0
 - Browser: Firefox
 - Command: `debug 0`, `debug 1`

**Describe the bug**

- `debug 0` returns an error due to `$.deparam` not being available
- `debug 1` (or 2) returns an error due to `$.param.querystring` not being available

The fix should be simple so I can open a PR if needed. Thank you!

**Expected behavior**
These commands should work.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Tardo** [comment]
Thanks for the report.

**Comment by Tardo** [comment]
Fixed here: https://github.com/Tardo/OdooTerminal/commit/f714c273512a18dbb3e0b7dc07ea6d8e316d4ca6
