### ISSUE TITLE
Error in query, read and search command [BUG] 

### ISSUE THREAD

**Issue by Paologg1** [Tardo/OdooTerminal#133]
First of all, check that you are using the latest version.

**Basic Info. (please complete the following information):**
 - Odoo version: [e.g. 16.0] and [e.g. 17.0]
 - Browser: [e.g. edge, chrome]
 - Command: `[e.g. read -m product.product -i XX -f *]`

**Describe the bug**
The shortcut to get the model does not work and when you enter it manually it throws the error 
[!] InvalidValueError: Invalid value 'product.product'

**Expected behavior**
The shortcut has to work correctly and return the expected query.

**Screenshots**
If applicable, 
![cap02](https://github.com/Tardo/OdooTerminal/assets/109562007/1cea454e-9434-4b56-9447-138fb9822458)
![cap01](https://github.com/Tardo/OdooTerminal/assets/109562007/9adeccd2-51e4-4c34-bf44-4388144e3767)
add screenshots to help explain your problem.

**Additional context**
translated from Spanish to English by DeepL

**Comment by Tardo** [comment]
Hi! thanks for the report!

Until the patch arrives, you can use:
```read -m product.product -i XX -f '*'```
** Notice the explicit string syntax

**Comment by Tardo** [comment]
Fixed here: https://github.com/Tardo/OdooTerminal/commit/2e18492ddb16ddba2a86ce8cc72f7bd0b19d1ab0
