### ISSUE TITLE
[BUG] Pressing ESC on all pages will result in an error notification

### ISSUE THREAD

**Issue by smomop** [Tardo/OdooTerminal#134]
First of all, check that you are using the latest version.

**Basic Info. (please complete the following information):**
 - Odoo version: odoo 14,odoo16,odoo17
 - Browser: arc,edge
 - Command: none

**Describe the bug**
Pressing ESC on all pages will result in an error notification
**Expected behavior**
Do not encounter any errors

**Screenshots**

**Additional context**
Error:
![CleanShot 2024-09-23 at 17 25 52@2x](https://github.com/user-attachments/assets/1ffa82ed-dd7b-4fb1-b640-b083fd6193e8)

Traceback:
`TypeError: Cannot read properties of undefined (reading 'classList')
    at Ys.hide (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/loader.mjs:1:231352)
    at chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/loader.mjs:1:254008
    at Generator.next (<anonymous>)
    at t (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/constants-BWoluOSz.mjs:1:197)
    at a (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/constants-BWoluOSz.mjs:1:400)
    at chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/constants-BWoluOSz.mjs:1:459
    at new Promise (<anonymous>)
    at chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/constants-BWoluOSz.mjs:1:340
    at jl.doHide (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/loader.mjs:1:254017)
    at jl.kl (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/loader.mjs:1:262478)`

**Comment by Tardo** [comment]
It seems that the extension is not starting correctly. Does the browser console throw any other messages since the page starts loading?

Does the bug happen in Odoo runbot (https://runbot.odoo.com/)?

Thank you.

**Comment by smomop** [comment]
> It seems that the extension is not starting correctly. Does the browser console throw any other messages since the page starts loading?
> 
> Does the bug happen in Odoo runbot (https://runbot.odoo.com/)?
> 
> Thank you.


Console Information
![CleanShot 2024-09-24 at 08 47 38@2x](https://github.com/user-attachments/assets/63f84eb7-5a03-4b3a-b496-e5b5573b48ec)

runbot pages
![CleanShot 2024-09-24 at 08 46 59@2x](https://github.com/user-attachments/assets/21f1aa85-b024-4559-baa3-fd95e0a0a4a4)
When I disable this extension
![CleanShot 2024-09-24 at 08 48 32@2x](https://github.com/user-attachments/assets/224aa51d-9aa4-4918-a6fc-c673fedeb71d)

**Comment by colu-odoo** [comment]
Same issue in Firefox

**Comment by Tardo** [comment]
Thanks for reporting! :)
Fixed here: https://github.com/Tardo/OdooTerminal/commit/97a30c2f4237a078a6829cd547b7daf69078b801

Releasing v11.5.2...
