### ISSUE TITLE
[BUG] Odoo 14.0 EE Chrome Doesn't call toggle term when using shortcut, Doesn't do anything when left clicking extension icon

### ISSUE THREAD

**Issue by rrebollo** [Tardo/OdooTerminal#135]
First of all, check that you are using the latest version.
![image](https://github.com/user-attachments/assets/6908ac73-0446-41ef-9f12-ee70c344a308)

**Basic Info. (please complete the following information):**
 - Odoo version: 14
 - Odoo Edition: enterprise
 - Browser: Chrome
 - Command: toggle_term

**Describe the bug**
When pressing shortcut or clicking extension icon nothing hapens
**Expected behavior**
Termial toggling
**Screenshots**
![image](https://github.com/user-attachments/assets/cffd019d-2a26-4ade-ad0c-e1b75827f4ba)
![image](https://github.com/user-attachments/assets/910372eb-fbbb-40c9-9282-7c9c1a821e44)
![image](https://github.com/user-attachments/assets/f7ae647d-383e-4a6b-91a4-7e1f0d958a4f)

**Additional context**
Extension looks like is active and with proper permissions.

**Comment by rrebollo** [comment]
It works like expected in v16 EE.

**Comment by rrebollo** [comment]
I see now: it doesn't work in /web#home. It works at sales, purchases ...

**Comment by rrebollo** [comment]
A colleague says it happens to him too but in v14 CE works like a charm. It looks like it's restricted to some urls v14 EE.

**Comment by Tardo** [comment]
I don't have a test environment to replicate. Can you try removing the keyboard shortcut from the extension settings? It's not needed anymore anyway (it's the browser's own settings, as you show in the image).

If you could give me more details... an example URL where you know what fails or some traceability that the browser shows... Thanks.

**Comment by rrebollo** [comment]
> I don't have a test environment to replicate. Can you try removing the keyboard shortcut from the extension settings? It's not needed anymore anyway (it's the browser's own settings, as you show in the image).
> 
> If you could give me more details... an example URL where you know what fails or some traceability that the browser shows... Thanks.

sorry It's a customer instance in odoo.sh, so ... Anyway, no big deal 'cause It doesn't work only in the [home](https://espumasdelvalles.odoo.com/web?debug=1#cids=1&home=). I did remove the shortcut setting from the extension but same behaviour. Also Chrome console doesn't show any errors or tips.
