### ISSUE TITLE
[BUG] wrong version on docker instances

### ISSUE THREAD

**Issue by micheledic** [Tardo/OdooTerminal#136]
First of all, check that you are using the latest version.

**Basic Info. (please complete the following information):**
 - Odoo version: all
 - Browser: Chrome

**Describe the bug**
On Odoo docker instance the version is trimmed 

**Expected behavior**
Full version or at least the odoo version without date 

**Screenshots**

On the status bar
![image](https://github.com/user-attachments/assets/64198b23-2801-4790-91eb-605b104cef4a)

The correct version:
![image](https://github.com/user-attachments/assets/7a41c829-689d-483b-966c-6bc5f69ca5bc)

**Comment by Tardo** [comment]
Thanks for report!

Should be fixed here: https://github.com/Tardo/OdooTerminal/commit/1a2e0fc683ca2364c09cf3cf5c150e0fe2acf654
