### ISSUE TITLE
[BUG] For loop executed more often than it should

### ISSUE THREAD

**Issue by omgMath** [Tardo/OdooTerminal#139]
First of all, check that you are using the latest version.

**Basic Info. (please complete the following information):**
 - Odoo version: 14.0
 - Browser: Firefox, Edge
 - Command: 
```
$aml = (search -m account.move.line -d [["move_id", "=", 2139], ["product_uom_id", "=", 5]])
for ($i = 0; $i < $aml['length']; $i += 1){ write -m account.move.line -i $aml[i].id -v { "product_uom_id": 1 } }
```

**Describe the bug**
In my case above search returned around 40 entries. However, the `for` loop was executed in way more often (I think it would have been executed infinitely often if I had not aborted the command).

**Expected behavior**
- The for loop is only executed as often as it should (in my case 40 times)
- The command is rejected, since there is a syntax error (`i` instead of `$i`, `.id` instead of `['id']`). The bug also persists if the syntax errors are fixed.

**Comment by Tardo** [comment]
Hi!
How many records are there?

try:
```
$aml = (search -m account.move.line -d [["move_id", "=", 2139], ["product_uom_id", "=", 5]])
for ($i = 0; $i < $aml['length']; $i += 1){ silent write -m account.move.line -i $aml[$i].id -v { "product_uom_id": 1 } }
```
- Use “silent” to disable screen printing
-  Change “i” to “$i” ($aml[i].id --> $aml[$i].id)


Although it is better to use:
```
$aml = (search -m account.move.line -d [["move_id", "=", 2139], ["product_uom_id", "=", 5]])
write -m account.move.line -i $aml['ids'] -v { "product_uom_id": 1 }
```

Let me know if you have any problems ;)

**Comment by omgMath** [comment]
Hi! Thanks for looking into this!

When I tried to reproduce the error, I realized this only seems to be happening in Firefox, but not in Edge.
>  How many records are there?
About 40

Hope the following screenshot clears things up:
![image](https://github.com/user-attachments/assets/8e3a9f9a-f725-4ff0-a99a-c8a6b1ff29b0)

I added the `-l 2`, so `$aml` should have length at most 2. But the `for` loop is executed more times. It was a bit hard to time the screenshot correctly, but the `for` loop is continuing infinitely in the background. The screenshot was taken ~0.5s after starting the loop.

Thanks for the hints!

**Comment by Tardo** [comment]
Ok, my mistake. The correct syntax is:
```
$aml = (search -m account.move.line -d [["move_id", "=", 2139], ["product_uom_id", "=", 5]])
for ($i = 0; $i < $aml['length']; $i += 1){ write -m account.move.line -i $aml[$i]['id'] -v { "product_uom_id": 1 } }
```
** And you are using v11.2.0 ... latest version is: 11.6.0

However, to avoid possible misunderstandings, the interpreter will now notify if it detects something incorrect: https://github.com/Tardo/OdooTerminal/commit/13b63148cd92807ab5a77ec5ea860ab2b571d327 :)
