### ISSUE TITLE
[BUG] Viewing model and subsequent accessing record results in creation form rather than records form

### ISSUE THREAD

**Issue by mads-vkd** [Tardo/OdooTerminal#140]
First of all, check that you are using the latest version.

**Basic Info. (please complete the following information):**
 - Odoo version: 16, 17 and 18. 15 No issue, it seems.
 - Browser: Chrome, Firefox
 - Command: view sale.order > go to record in list view.

**Describe the bug**
On any version 17 Odoo (and 16 and 18, tested both locally on outdated (+2 months olds versions) and via RunBot)
When viewing the records of a model by accessing the model via the command.
And then selecting one of those records.
You're taken to a "create" form, rather than the form for the records data.

**Expected behavior**
When selecting a recordset, you'd be shown the data of that record in form-view.

**Screenshots**
View model list:
![image](https://github.com/user-attachments/assets/edd3382e-cdaa-4b8f-bd94-01b327215a2d)

Access a record:
![image](https://github.com/user-attachments/assets/d0b130a2-4136-4abe-b594-f75ec1d3e99e)

**Additional context**
Can't quite find the piece of code from Odoo Terminal that could be the cause, but seems more unlikely it's a sweeping change across 3 version of Odoo that now causes new list-view windows to behave differently when accessing a recordset.

**Comment by Tardo** [comment]
Thanks! Fixed here: https://github.com/Tardo/OdooTerminal/commit/78cd5fd1b64e30266544717c21422fbc1c61d164

**Comment by Tardo** [comment]
Fixed in: v11.7.1 ;)
