### ISSUE TITLE
Allow batch operations

### ISSUE THREAD

**Issue by Yajo** [Tardo/OdooTerminal#19]
Commands `write` and `unlink` would benefit a lot from being able to pass a list of IDS instead of just one.

**Comment by Tardo** [comment]
Sounds good!
I will add a new parameters: "l" and "!" to define a list or a strict list

For example:
 - A command that can receive a list of ints or only an int:  "li"
 - A command that can receive only a list of ints: "!li"
 - A command that can receive a list of strings or only an string: "ls"
 - A command that can receive only a list of strings: "!ls"

**Comment by Tardo** [comment]
fixed in #20
