### ISSUE TITLE
New command `ref`

### ISSUE THREAD

**Issue by Yajo** [Tardo/OdooTerminal#25]
It would be nice if we had a `ref example_module.example_xmlid` command that searches among `ir.model.data` and returns the model + res_id combination that matches that/those ref/s.

**Comment by Tardo** [comment]
At the moment you can create a alias:
`alias ref call ir.model.data xmlid_to_res_model_res_id ["$1"]`

Using the alias: `ref base.model_res_partner`

The command will be added in #24 to support the usage of a list of xmlids

**Comment by Yajo** [comment]
Oooh I didn't know about `alias`. 🎸

**Comment by Tardo** [comment]
Added here: https://github.com/Tardo/OdooTerminal/pull/24/commits/95ebd691a05af4b4787aad7cc59d430549606979
