### ISSUE TITLE
Feature Request / Suggestion: Tab completion 

### ISSUE THREAD

**Issue by mohamedhagag** [Tardo/OdooTerminal#29]
Thank you guys for the great extension, your effort is really appreciated.

I think it will be a nice feature if we can have a tab completion feature.

BR,

**Comment by Tardo** [comment]
Thanks! What do you mean in particular? A basic auto-completion is currently implemented for the command name.

**Comment by mohamedhagag** [comment]
I mean for some commands attributes like install module names completion object names completion in CRUD functions.

It would be great.

**Comment by Tardo** [comment]
I would like to redo how commands are invoked so that input parameters by name can be used instead of by positioning. But still be compatible with the current system. So... i will try add full auto-completion feature.

New:
```
search -m res.partner -o name
search --model res.partner --order name
```

Current:
```search res.partner * [] 0 0 name```

**Comment by Tardo** [comment]
Initial implementation of "Commnad Assistant" done in 8.0.0 (can be improved):
![command_assistant](https://user-images.githubusercontent.com/731270/129745004-67ab90bc-0f22-41fd-870b-3ae54464b161.gif)
