### ISSUE TITLE
Suggestion: Option to easily export translation files for a given module

### ISSUE THREAD

**Issue by joao-p-marques** [Tardo/OdooTerminal#30]
It would be nice to have an easy way to export the translation files for a module, something like:

```
export_pot APP_NAME
```

**Comment by Tardo** [comment]
Done in 8.0.0:
`lang export` -> Open Export wizard
`lang import` -> Open Export wizard

`lang export -f po -m mail -l en_US` -> Export po translation for the 'mail' module
`lang import -f po -m mail -l es_ES -n Español`

`lang list`-> Show installed languages

**Comment by joao-p-marques** [comment]
Awesome! :tada: Thanks @Tardo, I just tested and it works great!

Just a small doubt: What is the difference between using the `--lang` option and the `--name` one? 

![image](https://user-images.githubusercontent.com/38977934/130572840-eea3e102-3a8f-4faa-bc30-a326327f3393.png)

AFAICS they both refer to the language, right? Could they be combined to avoid confusion?
