### ISSUE TITLE
Clicking on an ID after a search, to open its form, fails

### ISSUE THREAD

**Issue by Yajo** [Tardo/OdooTerminal#32]
STR:

1. `search -m hr.attendance -l 1`
2. Click on the ID.

Error 1:

    Server application error
    Error code: 200 
    Error message: Odoo Server Error 
    Error data message:
    400 Bad Request: <function Home.web_client at 0x7fd46c17eae8>, /web: Function declared as capable of handling request of type 'http' but called with a request of type 'json' 
    Error data debug:
    Traceback (most recent call last):
    File "/opt/odoo/custom/src/odoo/odoo/http.py", line 624, in _handle_exception
        return super(JsonRequest, self)._handle_exception(exception)
    File "/opt/odoo/custom/src/odoo/odoo/http.py", line 310, in _handle_exception
        raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
    File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
        raise value
    File "/opt/odoo/custom/src/odoo/odoo/http.py", line 669, in dispatch
        result = self._call_function(**self.params)
    File "/opt/odoo/custom/src/odoo/odoo/http.py", line 318, in _call_function
        raise werkzeug.exceptions.BadRequest(msg % params)
    werkzeug.exceptions.BadRequest: 400 Bad Request: <function Home.web_client at 0x7fd46c17eae8>, /web: Function declared as capable of handling request of type 'http' but called with a request of type 'json'
    ajax.js:35:25
    Uncaught (in promise) 
    Object { message: {…}, event: {…} }

Error 2:

    Uncaught (in promise) TypeError: fieldsViews is undefined
        setup https://localhost/web/static/src/js/views/view_dialogs.js:376
        promise callback*open https://localhost/web/static/src/js/views/view_dialogs.js:337
        OdooClass.extend/</prototype[name]</< https://localhost/web/static/src/js/core/class.js:90
        _cmdViewModelRecord moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/functions/backend.js:83
        _onClickTerminalView moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/functions/backend.js:97
        proxy https://localhost/web/static/src/js/core/mixins.js:277
        jQuery 8
        _delegateEvents https://localhost/web/static/src/js/core/widget.js:365
        setElement https://localhost/web/static/src/js/core/widget.js:321
        _injectTerminal moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/terminal.js:64
        _createTerminal moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/terminal.js:346
        init moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/terminal.js:121
        OdooClass.extend/</prototype[name]</< https://localhost/web/static/src/js/core/class.js:90
        init moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/functions/backend.js:16
        OdooClass.extend/Class.include/</prototype[name]</< https://localhost/web/static/src/js/core/class.js:123
        init moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/functions/fuzz.js:658
        OdooClass.extend/Class.include/</prototype[name]</< https://localhost/web/static/src/js/core/class.js:123
        init moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/functions/core.js:12
        OdooClass.extend/Class.include/</prototype[name]</< https://localhost/web/static/src/js/core/class.js:123
        init moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/functions/common.js:20
        OdooClass.extend/Class.include/</prototype[name]</< https://localhost/web/static/src/js/core/class.js:123
        Class https://localhost/web/static/src/js/core/class.js:107
        <anonymous> moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/loaders/backend.js:26
        jQuery 11
        <anonymous> moz-extension://1ea6ef43-b0a3-4f46-a9b0-f48dce51880f/odoo/js/loaders/backend.js:23
        def https://localhost/web/static/src/js/boot.js:260
        processJob https://localhost/web/static/src/js/boot.js:258
        processJobs https://localhost/web/static/src/js/boot.js:316
        def https://localhost/web/static/src/js/boot.js:271
        promise callback*processJob/def< https://localhost/web/static/src/js/boot.js:267
        processJob https://localhost/web/static/src/js/boot.js:258
        processJobs https://localhost/web/static/src/js/boot.js:316
        def https://localhost/web/static/src/js/boot.js:271
        promise callback*processJob/def< https://localhost/web/static/src/js/boot.js:267
        processJob https://localhost/web/static/src/js/boot.js:258
        processJobs https://localhost/web/static/src/js/boot.js:316
        def https://localhost/web/static/src/js/boot.js:271
        promise callback*processJob/def< https://localhost/web/static/src/js/boot.js:267
        processJob https://localhost/web/static/src/js/boot.js:258
        processJobs https://localhost/web/static/src/js/boot.js:316
        def https://localhost/web/static/src/js/boot.js:271
        promise callback*processJob/def< https://localhost/web/static/src/js/boot.js:267
        processJob https://localhost/web/static/src/js/boot.js:258
        processJobs https://localhost/web/static/src/js/boot.js:316
        define https://localhost/web/static/src/js/boot.js:154
        <anonymous> https://localhost/web#action=1062&cids=1&menu_id=763:635
    view_dialogs.js:376:20

**Comment by Tardo** [comment]
As always... thx for report!
