### ISSUE TITLE
[BUG] unclear error when calling metadata of a record that doesn't exist

### ISSUE THREAD

**Issue by yajo** [Tardo/OdooTerminal#42]
First of all, check that you are using the latest version.

**Basic Info. (please complete the following information):**
 - Odoo version: 12.0
 - Browser: firefox
 - Command: `metadata product.template 80255`

**Describe the bug**

    [!] Error executing 'metadata':
    create_uid is not defined

**Expected behavior**
Get metadata

**Screenshots**
![imagen](https://user-images.githubusercontent.com/973709/138266539-b6a81184-2ac1-4f91-b516-544027de0c78.png)

**Comment by Yajo** [comment]
OK I just realized that the problem is that there was no `product.template` with ID `80255`.

Probably the message could be clearer about that.
