### ISSUE TITLE
[BUG] UtilsBackend is undefined

### ISSUE THREAD

**Issue by dewingarcia** [Tardo/OdooTerminal#55]
- Odoo version: 14.0
 - Browser: firefox
 - Command: `lang -o export -l en_US -m mail`

**Bug**
when execute the command, show the next message
[!] Error executing 'lang':
UtilsBackend is undefined

**Expected behavior**
Finish the export lang file 

**Screen Shot**
![Screen Shot 2022-05-18 at 09 56 42](https://user-images.githubusercontent.com/11951010/169088113-45460c36-3205-4042-a5ba-3f2b031e26bb.png)

**Comment by Tardo** [comment]
Thanks for the report! it's fixed in 8.4.0

**Comment by dewingarcia** [comment]
it works perfectly
