### ISSUE TITLE
[BUG] Init commands

### ISSUE THREAD

**Issue by SantosJMM** [Tardo/OdooTerminal#63]
First of all, check that you are using the latest version.

**Basic Info. (please complete the following information):**
 - Odoo version: 14
 - Browser: chrome
 - Command: `print -m 'This is a example'`

**Describe the bug**
Testing the "Init Command". When the odoo tab is started or refreshed, it emits the error, coming from the plugin.

**Expected behavior**
I expected the message to be printed in the plugin console or in the browser queue

**Screenshots**
![image](https://user-images.githubusercontent.com/7267578/177219422-3b9f93ed-30e9-4e86-bf4c-69ad27b2b1cf.png)

**Additional context**
Null

**Comment by Tardo** [comment]
Thanks for report! should be fixed in 8.5.0
