### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dewingarcia** [Tardo/OdooTerminal#72]
**in firefox, the configuration window (Init Commands,terminal context) is not shown**
 - Odoo version: 14.0
 - Browser: firefox

**bug**
Version 8.6.0, in the Firefox browser dont show the extension Config/Preferences
in chrome works fine

**Expected behavior**
Show the extension Config/Preferences 

**Screenshots**
Firefox:
![image](https://user-images.githubusercontent.com/11951010/184039082-e1aaa186-76f0-4990-869c-1f599f9e019e.png)

Chrme;
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/11951010/184039109-64a45146-75aa-4863-8388-4b7aa14b1e34.png">

**Comment by Tardo** [comment]
In firefox you should be able to see the options from:
![2022-08-11_03-20](https://user-images.githubusercontent.com/731270/184049314-aa876c6b-4164-489d-b1b3-e49dac64bff8.png)

**Comment by dewingarcia** [comment]
Excellent. Thanks
