### ISSUE TITLE
[BUG] Init Commands

### ISSUE THREAD

**Issue by dewingarcia** [Tardo/OdooTerminal#88]
- Odoo version: 14.0
 - Browser: chrome, firefox
 - Command: Init Commands

**Describe the bug**
does not run init commands

**Expected behavior**
Execute init commands

**Screenshots**
![image](https://user-images.githubusercontent.com/11951010/202816087-25b1aac5-7370-48c6-ad66-c2a692eaf724.png)

**Comment by Tardo** [comment]
Thanks for the report and sorry for the late reply. This should be fixed in the next release.
