### ISSUE TITLE
[BUG] broken on master

### ISSUE THREAD

**Issue by mart-e** [Tardo/OdooTerminal#99]
**Basic Info:**
 - Odoo version: master
 - Browser: firefox
 - Command: n/a

**Describe the bug**
- Go to a runbot on master version
- Login with admin/admin
```
The following modules are needed by other modules but have not been defined, they may not be present in the correct asset bundle:

    web.view_dialogs

The following modules could not be loaded because they have unmet dependencies, this is a secondary error which is likely caused by one of the above problems:

    terminal.core.compat.15.Backend
    terminal.core.compat.16.Backend
    terminal.loaders.Backend
    terminal.functions.Backend
```

**Expected behavior**
Use the database

**Screenshots**
![Screenshot 2023-02-14 at 15-40-53 Odoo - Messages](https://user-images.githubusercontent.com/564822/218770464-bad1454e-079e-4428-a192-20fd2d45e252.png)

**Additional context**
The unloaded modules are now displayed since https://github.com/odoo/odoo/commit/c989ff339d1bb8afde3371d12dab8cc227941691

**Comment by Tardo** [comment]
Thanks for the report! At the moment I have chosen to make the "alpha" and "beta" versions incompatible.

**Comment by mart-e** [comment]
Thanks for the quick update but it seems this is still possible to reproduce on saas-16.1
![Screenshot 2023-02-23 at 11-12-29 Odoo](https://user-images.githubusercontent.com/564822/220878387-23a988be-1517-47fc-8714-7c1dc132b4f6.png)

(not always, refreshing the page solves this)

**Comment by Tardo** [comment]
OOps! thanks again for the report... i will made the change to not load in >16.0

** Winter is coming :S

**Comment by Tardo** [comment]
Ok, I hope it won't cause any more problems.
